### 

POST http://localhost:8000/api/v1/turmas/4/professores/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3NzYwNDU4MTV9.fnk-u5WmrqxuDl1-ef7rWVPANL26XSUMijoElGM9D-Y
