### 

POST http://localhost:8000/api/v1/turmas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3NzUzNjc4MjZ9.0kEp31XNIKXHU2nxSQNDBzu-FU87qVjqiqzrqLw694s

{
  "ano": 2026,
  "codigo": "20262-SO-M2",
  "data_fim": "2026-12-15",
  "data_inicio": "2026-08-05",
  "disciplina_id": 5,
  "horario": "08:30:00",
  "semestre": "2026.2"
}
