### 

POST http://localhost:8000/api/v1/turmas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3Nzg0NTQyOTh9.MzaCmqeUi8FVfmAyvmZ-m0QeuBU8i21DcsYWF3zizLY

{
  "ano": 2024,
  "codigo": "WEB404-A",
  "data_fim": "2024-06-30",
  "data_inicio": "2024-02-01",
  "disciplina_id": 6,
  "horario": "19:00:00",
  "semestre": "2024.1"
}
