### 

GET http://localhost:8000/api/v1/turmas/codigo/20261-ALGO-A HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3NzYwNDUyMzZ9.x0Qj671pBDm0V30IQXS9QD1jt5p3WDasw0aPbM8gf00
