### 

GET http://localhost:8000/api/v1/turmas/aluno/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJ2YW5hZ2lsYUBlbWFpbC5jb20iLCJ0aXBvIjoiQUxVTk8iLCJleHAiOjE3ODA5NzQ3ODF9.E9bI8wwU-ri10Fv5ij5erxfqc511cA0w1MMPmMfOAAw
