### 

POST http://localhost:8000/api/v1/disciplinas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3Nzg0NTQyOTh9.MzaCmqeUi8FVfmAyvmZ-m0QeuBU8i21DcsYWF3zizLY

{
  "codigo": "WEB404",
  "descricao": "HTML, CSS, JavaScript, React e desenvolvimento full-stack",
  "nome": "Programação Web"
}
