"""init_neon_db

Revision ID: cee6de032a67
Revises: 
Create Date: 2026-05-13 22:29:58.584975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cee6de032a67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ALUNO', 'PROFESSOR', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('registro_professor', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('registro_professor')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.String(length=6), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_turmas_id'), 'turmas', ['id'], unique=False)
    op.create_table('chamadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('coordenadas_professor', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raio', sa.Float(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'ENCERRADA', name='chamadastatus'), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamadas_id'), 'chamadas', ['id'], unique=False)
    op.create_table('turma_aluno',
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], )
    )
    op.create_table('turma_professor',
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], )
    )
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('chamada_id', sa.Integer(), nullable=True),
    sa.Column('coordenadas_aluno', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('distancia_calculada', sa.Float(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PRESENTE', 'AUSENTE', 'ABONADA', name='presencastatus'), nullable=True),
    sa.Column('abonado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_abono', sa.DateTime(), nullable=True),
    sa.Column('motivo_abono', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['abonado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['chamada_id'], ['chamadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'chamada_id', name='unique_aluno_chamada')
    ) 
    op.create_index(op.f('ix_presencas_id'), 'presencas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presencas_id'), table_name='presencas')
    op.drop_table('presencas')
    op.drop_table('turma_professor')
    op.drop_table('turma_aluno')
    op.drop_index(op.f('ix_chamadas_id'), table_name='chamadas')
    op.drop_table('chamadas')
    op.drop_index(op.f('ix_turmas_id'), table_name='turmas')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
