"""add_carga_horaria_to_disciplinas

Revision ID: f93f3d4cbb6c
Revises: 24bc968e2482
Create Date: 2026-05-13 20:41:15.467173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93f3d4cbb6c'
down_revision: Union[str, Sequence[str], None] = '24bc968e2482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplinas', sa.Column('carga_horaria', sa.Integer(), nullable=False, server_default='60'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplinas', 'carga_horaria')
    # ### end Alembic commands ###
