### 

POST http://localhost:8000/api/v1/chamadas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJwcm9mZXNzb3JsdWNhc0BlbWFpbC5jb20iLCJ0aXBvIjoiUFJPRkVTU09SIiwiZXhwIjoxNzc4NTQ5MjM1fQ.Z8yRXyw2BtN2l_VkZCYuThmAxTVX0axRpsgS5rQDt9w

{
  "coordenadas": {
    "latitude": -23.5505,
    "longitude": -46.6333
  },
  "raio": 50,
  "turma_id": 1
}
