### 

POST http://localhost:8000/api/v1/chamadas/6/encerrar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsImVtYWlsIjoicHJvZmVzc29yanVsaW9AZW1haWwuY29tIiwidGlwbyI6IlBST0ZFU1NPUiIsImV4cCI6MTc3NjExMzY0MH0.OZ6_KcHxJg5fFFM_4tCDbWqfHbJofJX7L5K7O2SD5ws
