### 

GET http://localhost:8000/api/v1/chamadas/3/relatorio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJ0aXBvIjoiQURNSU4iLCJleHAiOjE3NzgxMTA5OTB9.IYHB9GR85exA9OGNvYxft3tCGpSPGKG44aPzlndsPIM
