### 

POST http://localhost:8000/api/v1/presencas/abonar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJwcm9mZXNzb3JsdWNhc0BlbWFpbC5jb20iLCJ0aXBvIjoiUFJPRkVTU09SIiwiZXhwIjoxNzc4NDQ0MDg0fQ.dECDRnWJG-6P4ok35Cy6z2BH66nzN-ZQrhUo8icKGc0

{
  "motivo": "Reunião bolsista",
  "presenca_id": 10
}
