### 

POST http://localhost:8000/api/v1/presencas/registrar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhbHVub0BlbWFpbC5jb20iLCJ0aXBvIjoiQUxVTk8iLCJleHAiOjE3NzgxMDczNDd9.Xfj12T7uL5GRZQnjK9e6xNs0jqzCISWys67otum6FKk

{
  "chamada_id": 3,
  "coordenadas": {
    "latitude": -23.5500,
    "longitude": -46.6333
  }
}
